### ISSUE TITLE
Question about read VS write auth token

### ISSUE THREAD

**Issue by mockitoguy** [levithomason/github-changelog-api#3]
Is it ok if the auth token is read-only? E.g. the service will only generate the release notes and not push the changelog to my repo? It would be useful if this info was explicit in the docs.

Great job!!!

**Comment by mockitoguy** [comment]
Also, it would be good to warn the user to only disclose 'read-only' auth token for safety.

**Comment by levithomason** [comment]
Yep, the token only needs to be able to read your repo issues and PRs. It would be good to link to the original repo docs for token usage. PRs are very much welcomed!
