### ISSUE TITLE
Support Github Enterprise

### ISSUE THREAD

**Issue by nrodriguez** [levithomason/github-changelog-api#8]
Github Changelog Generator lets you set certain values to pull it from an enterprise version of github.

github_endpoint && github_site are two params you can pass. Any way to incorporate this into your app as well?

**Comment by levithomason** [comment]
Yep, that can be added as another query param in the same way the `token` param is handled.  See here:

https://github.com/levithomason/github-changelog-api/blob/master/server/index.js#L31

The logic is fairly straight forward from there.  The params are passed down to `generateChangelog` which eventually adds them to the child process that executes `github_changelog_generator`.

I'd gladly take a PR for this if you want to extend it.

**Comment by levithomason** [comment]
Housekeeping, PRs welcome.
